//#include <iostream>
//#include <exception>
//
//using namespace std;
//
//void foo(int input) {
//	try {
//	// valid input should be positive;
//	if (input > 0) {
//		// DoThings();
//	}
//	else {
//		throw exception("Invalid input!");
//	}
//
//	}
//	catch (exception &e) {}
//}
//
//void main() {
//	try {
//		foo(-1);
//	}
//	catch (exception &e) {
//		cout << e.what();
//	}
//}